"""add relationships

Revision ID: 6c13d8839bd5
Revises: a2dcf55f6ca8
Create Date: 2021-11-22 22:59:38.494648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c13d8839bd5'
down_revision = 'a2dcf55f6ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contact', ['id'])
    op.create_foreign_key(None, 'contact', 'user', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_constraint(None, 'contact', type_='unique')
    # ### end Alembic commands ###
